CREATE TABLE DISCIPLINA(
	DISCIPLINA VARCHAR(60) NOT NULL,
    SEMESTRE VARCHAR(7) NOT NULL,
    NOTA VARCHAR(4) NOT NULL,
    FALTA INT(3) NOT NULL,
	RGMALUNO INT(8),
    CONSTRAINT FK_DISCIPLINA_ALUNO FOREIGN KEY (RGMALUNO) REFERENCES ALUNO(RGMALUNO)
    ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB;
